# script: run general pipeline script
# description: sources the general pipeline scripts, ensures project
# dependencies are installed and loaded, then builds configuration and creates
# required directories.

if (!exists("get_pipeline_constants", mode = "function", inherits = TRUE)) {
  source(here::here("r", "0-general_pipeline", "01-setup", "01-constants.R"), echo = FALSE)
}


#' @title run general pipeline
#' @description executes the general pipeline bootstrap by sourcing helper
#' scripts, installing missing dependencies, loading dependencies, creating the
#' configuration object, and creating required directories.
#' @param dataset_name character scalar dataset identifier forwarded to
#' `load_pipeline_config()` to build dataset-specific audit paths.
#' @return named list pipeline configuration generated by
#' `load_pipeline_config()`.
#' @importFrom progressr handlers handler_txtprogressbar with_progress progressor
#' @importFrom checkmate assert_string
#' @examples
#' config <- run_general_pipeline("whep_data_raw")
#' names(config)
run_general_pipeline <- function(
  dataset_name = get_pipeline_constants()$dataset_default_name
) {
  checkmate::assert_string(dataset_name, min.chars = 1)
  pipeline_constants <- get_pipeline_constants()

  general_settings <- pipeline_constants$general_pipeline
  total_steps <- general_settings$total_steps
  progress_messages <- general_settings$progress_messages

  progressr::handlers(progressr::handler_txtprogressbar(
    width = general_settings$progress_bar_width,
    clear = FALSE
  ))

  config <- progressr::with_progress({
    progress <- progressr::progressor(along = seq_len(total_steps))

    # dynamically collect stage scripts in the general pipeline in-order
    general_stage_dirs <- c("00-dependencies", "01-setup", "02-helpers")

    general_scripts <- unlist(
      lapply(general_stage_dirs, function(d) {
        stage_path <- here::here("r", "0-general_pipeline", d)
        files <- list.files(stage_path, pattern = "\\.R$", full.names = FALSE)
        if (length(files) == 0) return(character(0))
        files <- sort(files)
        file.path(d, files)
      }),
      use.names = FALSE
    )

    # fail early if any expected script is missing
    missing_scripts <- general_scripts[!file.exists(here::here("r", "0-general_pipeline", general_scripts))]
    if (length(missing_scripts) > 0) {
      cli::cli_abort(c("Missing general pipeline scripts:", paste0("- ", missing_scripts)))
    }

    # source dependencies first
    dep_scripts <- general_scripts[grepl("^00-dependencies/", general_scripts)]
    for (script_name in dep_scripts) {
      source(here::here("r", "0-general_pipeline", script_name), echo = FALSE)
    }
    progress(progress_messages$source_scripts)

    # check/load dependencies
    check_dependencies(pipeline_constants$dependencies$required_packages)
    progress(progress_messages$check_dependencies)

    load_dependencies(pipeline_constants$dependencies$required_packages)
    progress(progress_messages$load_dependencies)

    # source setup scripts
    setup_scripts <- general_scripts[grepl("^01-setup/", general_scripts)]
    for (script_name in setup_scripts) {
      source(here::here("r", "0-general_pipeline", script_name), echo = FALSE)
    }

    config <- load_pipeline_config(dataset_name = dataset_name)
    progress(progress_messages$load_config)

    # source helper scripts
    helper_scripts <- general_scripts[grepl("^02-helpers/", general_scripts)]
    for (script_name in helper_scripts) {
      source(here::here("r", "0-general_pipeline", script_name), echo = FALSE)
    }

    create_required_directories(config$paths)
    progress(progress_messages$create_dirs)

    config
  })

  return(config)
}

pipeline_constants <- get_pipeline_constants()

if (isTRUE(getOption(pipeline_constants$auto_run_options$general, TRUE))) {
  config <- run_general_pipeline()
}
